name: Bump Branch Version
on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: Version Type
        options:
          - auto
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 18.7
        uses: actions/setup-node@v1
        with:
          version: 18.7
          registry-url: 'https://registry.npmjs.org'
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Detect type | Get Branch Name
        if: github.event.inputs == 'auto'
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Detect type | Determine type
        if: github.event.inputs == 'auto'
        shell: bash
        run: echo "type=${{ contains( steps.extract_branch.outputs.branch, 'feat/' ) && 'minor' || 'patch' }}" >> $GITHUB_OUTPUT
        id: def_type

      - run: |
          yarn version --${{ steps.def_type.outputs.def_type || github.event.inputs.version_type }} --no-git-tag-version
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: .
      - run: |
          git add .
          git commit -m 'chore: bump version ${{ steps.package-version.outputs.current-version}}'
          git push

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
