name: Bump Branch Version
on:
    workflow_dispatch:
        inputs:
            level:
                description: Level can be minor, patch
                type: choice
                options:
                    - auto
                    - minor
                    - patch
            ref:
                description: Target branch
                type: string
                default: master

jobs:
    get-level:
        name: Get release level
        runs-on: ubuntu-latest
        outputs:
            level: ${{ steps.get-level.outputs.level }}
        steps:
            - name: Detect type | Get Branch Name
              id: extract_branch
              if: inputs.level == 'auto'
              shell: bash
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

            - name: Detect type | Determine type
              id: detect-level
              if: inputs.level == 'auto'
              shell: bash
              run: echo "level=${{ contains( steps.extract_branch.outputs.branch, 'feat/' ) && 'minor' || contains( steps.extract_branch.outputs.branch, 'fix/' ) && 'patch' || '' }}" >> $GITHUB_OUTPUT

            - name: Get level
              id: get-level
              run: echo "level=${{ steps.detect-level.outputs.level || inputs.level }}" >> $GITHUB_OUTPUT

    get-bumped-version:
        name: Get bumped version
        needs: [get-level]
        uses: ./.github/workflows/bump-version.yml
        with:
            repository: ${{ github.repository }}
            ref: ${{ inputs.ref }}
            level: ${{ needs.get-level.outputs.level }}

    update-version:
        name: Update version
        runs-on: ubuntu-latest
        needs: [get-bumped-version]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com

            - uses: actions/github-script@v6
              id: bump-version
              env:
                  NEW_VERSION: ${{ needs.get-bumped-version.outputs.version }}
              with:
                  script: |
                      const fs = require('fs');
                      const os = require('os');
                    
                      fs.readFile('./package.json', (err, data) => {
                          if (err) throw err;
                  
                          let packageJsonObj = JSON.parse(data);
                          packageJsonObj.version = `${ process.env.NEW_VERSION }`;
                          packageJsonObj = JSON.stringify(packageJsonObj, null, 2);
                  
                          fs.writeFile('./package.json', packageJsonObj + os.EOL, (err) => {
                              if (err) throw err;
                              console.log('The file has been saved!');
                          });
                      });

            - run: |
                  git add .
                  git commit -m 'chore: bump version ${{ needs.get-bumped-version.outputs.version }}'
                  git push

env:
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
