name: Bump Branch Version
on:
    workflow_dispatch:
        inputs:
            level:
                description: Level can be minor, patch
                type: choice
                default: auto
                options:
                    - auto
                    - minor
                    - patch
            ref:
                description: Target branch
                type: string
                default: master

jobs:
    bump-version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Setup Git
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com

            - name: Git auto merge
              # Reference: https://stackoverflow.com/a/8641053/8175165
              run: |
                  git checkout ${{ inputs.ref}}
                  git checkout ${{ github.head_ref || github.ref_name }}
                  : # action will abort if conflict error occurs here
                  git merge --no-commit --no-ff ${{ inputs.ref}}

            - name: Git commit change if being merged
              continue-on-error: true
              run: |
                  git merge --abort
                  : # If no changes, then nothing will be committed
                  git merge ${{ inputs.ref}} --no-edit

            - name: Extract branch name
              # Reference: https://stackoverflow.com/a/58035262/8175165
              id: extract_branch
              if: inputs.level == 'auto'
              shell: bash
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

            - name: Determine bump type
              id: bump_type
              if: inputs.level == 'auto'
              env:
                  auto_type: ${{ contains( steps.extract_branch.outputs.branch, 'feat/' ) && 'minor' || 'patch' }}
              shell: bash
              run: |
                  echo "type=${{ env.auto_type || inputs.level }}" >> $GITHUB_OUTPUT

            - name: Bump version
              run: |
                  yarn version --${{ steps.bump_type.outputs.type }} --no-git-tag-version

            - name: Get bumped version
              id: package-version
              run: |
                  echo "version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT

            - name: Push code
              run: |
                  git add .
                  git commit -m 'chore: bump version ${{ steps.package-version.outputs.version}}'
                  git push
