name: Bump Branch Version
on:
    workflow_dispatch:
        inputs:
            level:
                description: Level can be major/minor/patch. 'auto' only support minor/patch, depends on the prefix of branch name
                type: choice
                options:
                    - auto
                    - major
                    - minor
                    - patch
            ref:
                description: Target branch
                type: string
                default: master

jobs:
    bump-version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Setup Git
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com

            - name: Git auto merge
              # Reference: https://stackoverflow.com/a/8641053/8175165
              run: |
                  git merge --no-commit --no-ff master
                  : # action will abort if conflict error occurs here
                  git merge --abort
                  git merge master --no-edit
                  : # If no changes, then nothing will be committed

            - name: Extract branch name
              # Reference: https://stackoverflow.com/a/58035262/8175165
              id: extract_branch
              if: github.event.inputs.version_type == 'auto'
              shell: bash
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

            - name: Determine bump type
              id: bump_type
              if: github.event.inputs.version_type == 'auto'
              shell: bash
              run: |
                  echo "auto_type=${{ contains( steps.extract_branch.outputs.branch, 'feat/' ) && 'minor' || 'patch' }}"
                  echo "type=${{ auto_type || github.event.inputs.version_type }}" >> $GITHUB_OUTPUT

            - name: Bump version
              run: |
                  yarn version --${{ steps.bump_type.outputs.type }} --no-git-tag-version

            - name: Get bumped version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.3.1

            - name: Push code
              run: |
                  git add .
                  git commit -m 'chore: bump version ${{ steps.package-version.outputs.current-version}}'
                  git push
