on:
    workflow_call:
        inputs:
            repository:
                required: true
                type: string
            ref:
                required: true
                type: string
        outputs:
            version:
                description: The version read
                value: ${{ jobs.read-version.outputs.version }}

jobs:
    read-version:
        name: Output version from package.json
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.read-package-version.outputs.version }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  repository: ${{ inputs.repository }}
                  ref: ${{ inputs.ref }}

            - name: Read package version
              id: read-package-version
              run: |
                  PACKAGE_VERSION=$(node -p "require('./package.json').version")
                  echo "version=${ PACKAGE_VERSION }" >> $GITHUB_OUTPUT
